import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
  oxc: {
    jsx: {
      runtime: 'automatic',
      importSource: 'react',
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    globals: true,
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
    exclude: ['node_modules', '.next', 'dist'],
    testTimeout: 15000,
    fileParallelism: false,
  },
  resolve: {
    // Order matters: Vite matches alias keys in insertion order, so the more
    // specific `@convex/_generated` entry must come before the general one.
    alias: {
      '@': path.resolve(__dirname, '.'),
      // `backend/convex/_generated` is regenerated by `convex dev`/`codegen`
      // and is gitignored, so it does not exist in a clean checkout (CI,
      // Docker, or a fresh clone). The frontend deliberately resolves the
      // generated client to the committed deployment-independent shims in
      // `frontend/convex/_generated/`, exactly as `tsconfig.json` `paths`
      // does. Pointing tests at the backend directory instead made the suite
      // depend on untracked build artifacts and pass only on machines that had
      // already run the backend.
      '@convex/_generated': path.resolve(__dirname, 'convex/_generated'),
      '@convex': path.resolve(__dirname, '../backend/convex'),
    },
  },
});
