/**
 * Frontend shim for Convex generated data-model types.
 *
 * The backend's real `convex/_generated/dataModel` is regenerated by
 * `convex dev`/`codegen` and is gitignored, so it is absent in git-based
 * (CI / Docker / Dokploy) builds. The frontend only consumes the branded
 * `Id` type, so we expose a deployment-independent shim here — mirroring the
 * committed `api.ts` shim that uses `anyApi`. Wired via the tsconfig path
 * `@convex/_generated/dataModel`.
 */
import type { GenericId } from "convex/values";

/** Any Convex table name (frontend is decoupled from the backend schema). */
export type TableNames = string;

/**
 * A branded document id. `Id<'tasks'>` etc. stay assignment-compatible with
 * the real generated `Id` while not requiring the backend schema at build time.
 */
export type Id<TableName extends string = string> = GenericId<TableName>;
