import type { Metadata } from 'next';
import { absoluteUrl } from '@/lib/site';
import {
  DocsCallout,
  DocsH1,
  DocsH2,
  DocsInlineCode,
  DocsLead,
  DocsList,
  DocsP,
  DocsTable,
} from '@/components/docs/primitives';

export const metadata: Metadata = {
  title: 'Configuration — TaskLabs docs',
  description:
    'Environment files, required variables, origins, and CORS rules for TaskLabs.',
  alternates: { canonical: absoluteUrl('/docs/configuration') },
};

const REQUIRED_VARS: [string, string][] = [
  ['FRONTEND_ORIGIN', 'Public origin of the frontend (e.g. https://tasklabs.example.com).'],
  ['NEXT_PUBLIC_CONVEX_URL', 'Convex API origin the browser connects to.'],
  ['CONVEX_SERVER_URL', 'Server-side Convex URL for rendering and route handlers.'],
  ['CONVEX_SELF_HOSTED_ADMIN_KEY', 'Admin key generated by the backend container. Never commit.'],
  ['POSTGRES_URL', 'Postgres cluster URL only — no /<database> path.'],
  ['SITE_URL', 'Public site URL for Convex Auth.'],
  ['JWT_PRIVATE_KEY', 'Generated Convex Auth signing key.'],
  ['JWKS', 'Generated Convex Auth public key set.'],
  ['TELEGRAM_API_ORIGIN', 'Telegram API origin required by the frontend CSP and Telegram actions.'],
  ['TELEGRAM_WEBHOOK_ORIGIN', 'Public HTTPS Convex site origin for the Telegram webhook.'],
  ['CORS_ALLOWED_ORIGINS', 'Comma-separated exact-origin allow-list for browser CORS.'],
];

export default function DocsConfigurationPage() {
  return (
    <>
      <DocsH1>Configuration</DocsH1>
      <DocsLead>
        TaskLabs reads all runtime configuration from explicit environment
        values. There are no hardcoded ports, origins, credentials, or secrets
        in the Compose files, Dockerfiles, or application code.
      </DocsLead>

      <DocsH2 id="env-files">Environment files</DocsH2>
      <DocsList
        items={[
          <>
            <strong>.env.example</strong> — documented template for the
            production stack.
          </>,
          <>
            <strong>.env</strong> — gitignored production values used by the
            production Compose file.
          </>,
          <>
            <strong>.env.dev.example</strong> — documented template for the dev
            stack.
          </>,
          <>
            <strong>.env.dev</strong> — gitignored dev values used by the dev
            Compose file.
          </>,
        ]}
      />
      <DocsP>
        Copy the matching example file, fill every value, and never commit real
        secrets. Both example files are tracked; the filled files are
        gitignored.
      </DocsP>

      <DocsH2 id="required-vars">Required variables</DocsH2>
      <DocsTable
        head={['Variable', 'Purpose']}
        rows={REQUIRED_VARS.map(([name, purpose]) => [
          <DocsInlineCode key={name}>{name}</DocsInlineCode>,
          purpose,
        ])}
      />
      <DocsP>
        Compose interpolation uses <code>{'${VAR:?missing}'}</code> so a missing
        required value fails fast at startup instead of silently defaulting.
      </DocsP>

      <DocsH2 id="origins">Origins & CORS</DocsH2>
      <DocsP>
        Origins are explicit and never inferred. <code>FRONTEND_ORIGIN</code>{' '}
        and <code>CORS_ALLOWED_ORIGINS</code> must list exact origins. The MCP
        endpoint validates the request Host (or the first proxy-forwarded host)
        and any browser Origin against this allow-list.
      </DocsP>
      <DocsCallout tone="warning" title="No wildcard CORS">
        TaskLabs never uses wildcard CORS or local fallback origins in
        production. If a proxy fronts the app, its forwarded host must appear in
        the allow-list too.
      </DocsCallout>

      <DocsH2 id="rules">Rules to keep</DocsH2>
      <DocsList
        items={[
          <>Do not add fallback defaults like <code>{'${VAR:-value}'}</code> for runtime env.</>,
          <>Keep <code>POSTGRES_URL</code> cluster-only; a {'/<database>'} path makes the Convex backend exit.</>,
          <>Keep <code>.env</code>, <code>.env.dev</code>, and <code>.env.local</code> files out of commits.</>,
          <>Sync Convex deployment env from <code>.env.dev</code> before starting <code>convex dev</code>.</>,
          <>Leave <code>TELEGRAM_WEBHOOK_ORIGIN</code> empty until a real public HTTPS origin exists.</>,
        ]}
      />
    </>
  );
}
